apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    {{- include "web.labels" . | nindent 4 }}
    version: v1
spec:
  selector:
    matchLabels:
      {{- include "web.selectorLabels" . | nindent 6 }}
      version: v1
  {{- if .Values.global.updateStrategy }}
  replicas: {{ .Values.web.replicaCount }}
  strategy: {{- toYaml .Values.global.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "web.selectorLabels" . | nindent 8 }}
        version: v1
    spec:
      serviceAccountName: {{ template "app.serviceAccountName" . }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
              weight: 100
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets: {{- toYaml .Values.global.imagePullSecrets | nindent 4 }}
      {{- end }}
      containers:
        {{- if .Values.web.extraSideContainers }}
        {{ tpl .Values.web.extraSideContainers . | indent 8 }}
        {{- end }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          {{- if .Values.web.command }}
          command:
          {{ tpl .Values.web.command . | indent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.web.containerPorts.http }}
          {{- if .Values.web.resources }}
          resources: {{- toYaml .Values.web.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.web.extraVolumeMounts }}
          {{- toYaml .Values.web.extraVolumeMounts | nindent 12 }}
      {{- end }}
      {{- if .Values.web.extraInitContainers }}
      initContainers:
      {{ tpl .Values.web.extraInitContainers . | indent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.web.extraVolumes }}
      {{- toYaml .Values.web.extraVolumes | nindent 8 }}
  {{- end }}