server:
  forward-headers-strategy: framework
  shutdown: graceful
  port: ${PORT:8080}

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  cloud:
    stream:
      bindings:
        postEventPublisher-out-0:
          destination: posts
        postEventConsumer-in-0:
          destination: posts
          group: posts-group-${random.uuid}
  thymeleaf:
    cache: true
  graphql:
    graphiql:
      enabled: false

security:
  authentication:
    token:
      cookie-domain: localhost
      access_token_cookie-name: accessToken
      refresh_token_cookie-name: refreshToken
      access_token_validity-in-seconds: 86400
      refresh_token_validity-in-seconds: 259200
    security-matcher:
      ignore-patterns:
        - /favicon.ico
      permit-all-patterns:
        - /actuator/**
        - /api/v1/auth/**
        - /api/v1/nonsecure/**
        - /graphql
        - /subscriptions
        - /redirect
  content-security-policy: "script-src 'self'"

recaptcha:
  enabled: true
  verify-url: https://www.google.com/recaptcha/api/siteverify
  threshold: 0.5

chatgpt:
  base-url: https://api.openai.com/v1
  gpt-model: text-davinci-003
  audio-model: whisper-1
  moderation-model: text-moderation-latest
  temperature: 1.0
  maxTokens: 300
  image:
    number: 1
    size: LARGE

app:
  mail:
    from:
      enabled: false
      default:
    baseUrl: http://localhost:3000
  cache:
    redis:
      time-to-live-seconds: 3600
    serializer:
      valueType: JSON

springdoc:
  api-docs:
    enabled: false