version: '3.8'

volumes:
  mongodb:

networks:
  backend:
    name: backend
  frontend:
    name: frontend

services:
  mongodb:
    image: mongo:5.0
    restart: unless-stopped
    container_name: mongodb
    networks:
      - backend
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGODB_DATABASE
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
    volumes:
      - ./mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - mongodb:/data/db
    ports:
      - "27018:27017"

  spring-graphql-service:
    image: suayb/spring-graphql-samples:latest
    restart: unless-stopped
    container_name: spring-graphql-service
    depends_on:
      - mongodb
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod,websocket
      - PORT
      - SPRING_DATA_MONGODB_URI
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS
      - SECURITY_AUTHENTICATION_TOKEN_PUBLIC_KEY
      - SECURITY_AUTHENTICATION_TOKEN_PRIVATE_KEY
      - SECURITY_AUTHENTICATION_TOKEN_VALIDITY_IN_SECONDS
      - SECURITY_AUTHENTICATION_TOKEN_COOKIE_DOMAIN
      - SECURITY_CIPHER_BASE64_SECRET
      - SECURITY_AUTHENTICATION_SECURITY_MATCHER_IGNORE_PATTERNS
      - SECURITY_AUTHENTICATION_SECURITY_MATCHER_PERMIT_ALL_PATTERNS
      - RECAPTCHA_ENABLED
      - RECAPTCHA_VERIFY_URL
      - RECAPTCHA_SECRET_KEY
      - RECAPTCHA_THRESHOLD
      - CHATGPT_BASE_URL
      - CHATGPT_SECRET_KEY
      - CHATGPT_GPT_MODEL
      - CHATGPT_AUDIO_MODEL
      - CHATGPT_MODERATION_MODEL
      - CHATGPT_TEMPERATURE
      - CHATGPT_MAX_TOKENS
      - CHATGPT_IMAGE_NUMBER
      - CHATGPT_IMAGE_SIZE
      - SPRING_MAIL_HOST
      - SPRING_MAIL_PORT
      - SPRING_MAIL_USERNAME
      - SPRING_MAIL_PASSWORD
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST
      - APP_MAIL_FROM_ENABLED
      - APP_MAIL_FROM_DEFAULT
      - APP_MAIL_BASE_URL
    ports:
      - "9091:9091"
  web:
    image: suayb/spring-graphql-samples-web:latest
    restart: unless-stopped
    container_name: web
    networks:
      - frontend
    ports:
      - '3000:3000'