version: 2.1

orbs:
  snyk: snyk/snyk@1.4.0

aliases:
  - &maven-settings-file
      "\"<settings xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd' xmlns='http://maven.apache.org/SETTINGS/1.1.0'
              xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
            <servers>
              <server>
                   <id>github</id>
                   <username>$GITHUB_USERNAME</username>
                   <password>$GITHUB_PASSWORD</password>
              </server>
              <server>
                    <id>registry-1.docker.io</id>
                    <username>$DOCKER_REGISTRY_USERNAME</username>
                    <password>$DOCKER_REGISTRY_PASSWORD</password>
              </server>
            </servers>
          </settings>\""
commands:
  generate-maven-settings-file:
    parameters:
      settings-file:
        type: string
    steps:
      - run:
          name: Generate Maven Settings File
          command: |
            mkdir -p ~/.m2
            echo -e << parameters.settings-file >> > ~/.m2/settings.xml
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.10.2
      docker_layer_caching: true
      resource_class: medium
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx6400m
    steps:
      - checkout
      - generate-maven-settings-file:
          settings-file: *maven-settings-file
      - run:
          name: Print Java Version
          command: java -version
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Download Dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: true
          severity-threshold: low
          token-variable: SNYK_TOKEN
#      - run:
#          name: Test
#          command: mvn -ntp clean verify
#      - run:
#          name: Packaging
#          command: mvn -ntp package -DskipTests
      - run:
          name: Quality Analysis
          command: mvn -ntp -Psonar initialize sonar:sonar -Dsonar.login=$SONAR_TOKEN
      - run:
          name: Publish Docker
          command: mvn -Pnative spring-boot:build-image -DskipTests -Dspring-boot.build-image.publish=true