version: 2.1

orbs:
  snyk: snyk/snyk@1.4.0

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.10.2
      docker_layer_caching: true
      resource_class: medium
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx6400m
    steps:
      - checkout
      - run:
          name: Print Java Version
          command: java -version
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Download Dependencies
          command: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: true
          severity-threshold: low
          token-variable: SNYK_TOKEN
#      - run:
#          name: Test
#          command: mvn -ntp clean verify
#      - run:
#          name: Packaging
#          command: mvn -ntp package -DskipTests
      - run:
          name: Quality Analysis
          command: mvn -ntp -Psonar initialize sonar:sonar -Dsonar.login=$SONAR_TOKEN
      - run:
          name: Publish Docker
          command: mvn -Pnative spring-boot:build-image -Dspring-boot.build-image.publish=true -Ddocker.credentials.username=$DOCKER_REGISTRY_USERNAME -Ddocker.credentials.password=$DOCKER_REGISTRY_PASSWORD -DskipTests