global:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  imagePullSecrets: []

serviceAccount:
  name: default

token:
  validityInSeconds: 86400
  cookieDomain: springgqlmsweb.susimsek.github.io

database:
  user: user
  password: iXCjXb7e2yjJbjRu

cipher:
  secret: secureCDCKey

chatgpt:
  model: text-davinci-003
  temperature: 1.0
  maxTokens: 300
  secret: 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

recaptcha:
  enabled: true
  threshold: 0.5
  secret: 6Lca17IjAAAAAAEpjSTErRO4Rw6z9lHqVAohwWdW

mail:
  host: smtp.gmail.com
  port: 587
  username: "*****"
  password: "*****"
  smtp:
    auth: true
    starttls:
      enable: true
  from:
    enabled: false
    default:
  baseUrl: http://springgqlmsweb.susimsek.github.io

spring:
  profiles:
    active: prod,websocket

springGraphqlService:
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 4
    targetCPU: 80
    targetMemory: 80
  replicaCount: 2
  containerPorts:
    http: 9091
  image:
    repository: suayb/spring-graphql-samples
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 9091
    clusterIP:
    loadBalancerIP:
  ingress:
    enabled: true
    certManager: false
    annotations:
      kubernetes.io/ingress.class: "nginx"
    path: /
    hostName: api.springgqlmsweb.susimsek.github.io
    tls: [ ]
  environment:
  resources:
    requests:
      cpu: 800m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  readinessProbe:
    enabled: true
    httpGet:
      path: /actuator/health/readiness
      port: http
      scheme: HTTP
      httpHeaders: [ ]
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 6
    successThreshold: 1
  livenessProbe:
    enabled: true
    httpGet:
      path: /actuator/health/liveness
      port: http
      scheme: HTTP
      httpHeaders: [ ]
    initialDelaySeconds: 1
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
    successThreshold: 1
  customLivenessProbe: { }
  customReadinessProbe: { }
  extraVolumeMounts: [ ]
  extraVolumes: [ ]

web:
  replicaCount: 1
  containerPorts:
    http: 3000
  image:
    repository: suayb/spring-graphql-samples-web
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000
    clusterIP:
    loadBalancerIP:
  ingress:
    enabled: true
    certManager: false
    annotations:
      kubernetes.io/ingress.class: "nginx"
    path: /
    hostName: springgqlmsweb.susimsek.github.io
    tls: []
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 250Mi
  extraVolumeMounts: []
  extraVolumes: []