apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-gql-service-configmap
  labels:
  {{- include "spring-gql-service.labels" . | nindent 4 }}
data:
  {{- if .Values.springGraphqlService.environment }}
  {{- range $key, $val := .Values.springGraphqlService.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
  SPRING_PROFILES_ACTIVE: {{ .Values.spring.profiles.active }}
  PORT: {{ .Values.springGraphqlService.containerPorts.http | quote}}
  SECURITY_AUTHENTICATION_TOKEN_BASE64_SECRET: ${TOKEN_SECRET}
  SECURITY_CIPHER_BASE64_SECRET: ${CIPHER_SECRET}
  SECURITY_AUTHENTICATION_TOKEN_TOKEN_VALIDITY_IN_SECONDS: {{ .Values.token.tokenValidityInSeconds| quote }}
  SPRING_DATA_MONGODB_URI: mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@mongodb:27017/demo