apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-gql-service-config
  labels:
  {{- include "spring-gql-service.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.springGraphqlService.containerPorts.http | quote}}
  SPRING_DATA_MONGODB_URI: mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@mongodb:27017/demo
  SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: kafka:9092
  SECURITY_AUTHENTICATION_TOKEN_PUBLIC_KEY: ${TOKEN_PUBLIC_KEY}
  SECURITY_AUTHENTICATION_TOKEN_PRIVATE_KEY: ${TOKEN_PRIVATE_KEY}
  SECURITY_AUTHENTICATION_TOKEN_VALIDITY_IN_SECONDS: {{ .Values.token.validityInSeconds| quote }}
  SECURITY_AUTHENTICATION_TOKEN_COOKIE_DOMAIN: {{ .Values.token.cookieDomain }}
  SECURITY_CIPHER_BASE64_SECRET: ${CIPHER_SECRET}
  SECURITY_AUTHENTICATION_SECURITY_MATCHER_IGNORE_PATTERNS: /favicon.ico
  SECURITY_AUTHENTICATION_SECURITY_MATCHER_PERMIT_ALL_PATTERNS: /actuator/**, /graphql, /subscriptions
  RECAPTCHA_ENABLED: {{ .Values.recaptcha.enabled }}
  RECAPTCHA_VERIFY_URL: https://www.google.com/recaptcha/api/siteverify
  RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET}
  SPRING_GRAPHQL_CORS_ALLOWED_ORIGINS: http://springgqlmsweb.susimsek.github.io
  RECAPTCHA_THRESHOLD: {{ .Values.recaptcha.threshold }}
  CHATGPT_BASE_URL: https://api.openai.com/v1
  CHATGPT_SECRET_KEY: ${CHATGPT_SECRET}
  CHATGPT_MODEL: {{ .Values.chatgpt.model }}
  CHATGPT_TEMPERATURE: {{ .Values.chatgpt.temperature }}
  CHATGPT_MAX_TOKENS: {{ .Values.chatgpt.maxTokens }}
  SPRING_MAIL_HOST: {{ .Values.mail.host }}
  SPRING_MAIL_PORT: {{ .Values.mail.port }}
  SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
  SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: {{ .Values.mail.smtp.auth }}
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: {{ .Values.mail.smtp.starttls.enable }}
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: {{ .Values.mail.host }}
  APP_MAIL_FROM_ENABLED: {{ .Values.mail.from.enabled }}
  APP_MAIL_FROM_DEFAULT: {{ .Values.mail.from.default }}