apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-gql-service-config
  labels:
  {{- include "spring-gql-service.labels" . | nindent 4 }}
data:
  application.yml: |-
    spring:
      config:
        activate:
          on-profile: {{ .Values.spring.profiles.active }}
      data:
        mongodb:
          uri: mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@mongodb:27017/demo
    security:
      authentication:
        token:
          public-key: ${TOKEN_PUBLIC_KEY}
          private-key: ${TOKEN_PRIVATE_KEY}
          token-validity-in-seconds: {{ .Values.token.tokenValidityInSeconds| quote }}
        security-matcher:
          ignore-patterns:
            - /favicon.ico
          permit-all-patterns:
            - /actuator/**
            - /graphql
            - /subscriptions
      cipher:
        base64-secret: ${CIPHER_SECRET}
    server:
      port: {{ .Values.springGraphqlService.containerPorts.http | quote}}
    dummy:
      message: this is new dummy message