apiVersion: v1
kind: Secret
metadata:
  name: token-secret
type: Opaque
data:
  TOKEN_SECRET: NjhkOGZmNmY4NGQ1ODFiMjI5M2JjZTJmYTRlMWVjNmM2Nzk2YjFiZTc2Nzc3MjMxMTE4Njg2ZjlhNTRhNmE0YmZhMzI5MDczZjQyZTZlZDFlYzdhZGZkYTUzZGUyMTMyM2VkZWRmNTEwZGQzNzc1YzIwMGRmYTFiNzAwNmI4Njc=