apiVersion: v1
kind: Secret
metadata:
  name: email-secret
type: Opaque
data:
  MAIL_USERNAME: {{ .Values.mail.username | b64enc | quote }}
  MAIL_PASSWORD: {{ .Values.mail.password | b64enc | quote }}